N_("About GPX Trip Planner")
N_("Enter Bookmark Name")
N_("Waypoints")
N_("Routes")
N_("Tracks")
N_("Search")
N_("POI")
N_("Photo")
N_("Error")
N_("Off")
N_("On")
N_("Follow")
N_("GPX Trip Planner")
N_("_File")
N_("Import from GPSr")
N_("Import from File")
N_("Import Preprocessed Tracks")
N_("Load Photographs")
N_("Document Properties")
N_("Offline Mode")
N_("_Edit")
N_("Sync JOSM's View")
N_("_View")
N_("Fullscreen")
N_("Sidebar")
N_("No Crop Lines")
N_("8.5\" x 11\" Crop Lines")
N_("11\" x 8.5\" Crop Lines")
N_("Lat/Lon Format: ddd.ddddd°")
N_("Lat/Lon Format: ddd°mm'ss.s\"")
N_("_Bookmarks")
N_("Add Bookmark")
N_("_Tools")
N_("Adjust the route to follow roads and add\n" \
             "a point at each turn. The added points will\n" \
             "be pink and be of type \"maneuver\".")
N_("Flesh Out Route")
N_("Remove excess points from route by merging\n" \
             "each of the guide points which you placed\n" \
             "into the next maneuver point.")
N_("Pare Down Route")
N_("Remove pink (maneuver) points from route.")
N_("Strip Route")
N_("Reverse Route")
N_("Precache Tiles")
N_("Reload Tiles")
N_("Associate GPX and LOC Files")
N_("Update Program")
N_("_Help")
N_("Name")
N_("Comment")
N_("Description")
N_("Symbol")
N_("Choose")
N_("Coordinates")
N_("Source")
N_("Type")
N_("Time")
N_("Elevation")
N_("Link")
N_("+ Route Point-->")
N_("Add Selected Waypoint as:")
N_("Display Color")
N_("+ Waypoint")
N_("Add Selected Route Point as:")
N_("Add Selected Track Point as:")
N_("Anywhere")
N_("In USA")
N_("Within Viewport")
N_("Add Selected Search Result as:")
N_("Add Selected POI as:")
N_("Filename")
N_("Live GPS:")
N_("Send To")
N_("-")
N_("+")
N_("Manipulate:")
N_("Tool:")
N_("Select")
N_("Adjust")
N_("Draw")
N_("Delete")
N_("Choose Map Symbol")
N_("DocumentProperties")
N_("Author's Name")
N_("Copyright Holder")
N_("File's Hyperlink Name")
N_("Author's E-mail")
N_("Author's Hyperlink Name")
N_("Copyright Year")
N_("Copyright License")
N_("Author's Hyperlink URL")
N_("Author's Hyperlink Type")
N_("File's Hyperlink URL")
N_("File's Hyperlink Type")
N_("@")
N_("Revision Time")
N_("Keywords")
N_("Unsaved Changes")
N_("There are unsaved changes.")
N_("Question")
